#!/bin/zsh

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

echo -n "백준 문제 번호: "
read -r problem_number

solution_file="$DIR/boj/$problem_number.py"
problem_link="https://www.acmicpc.net/problem/$problem_number"
problem_name=$(curl -s -N "$problem_link" | sed -n "s/^.*<title>\(.*\)<\/title>.*$/\1/p")

echo "# $problem_name" >> "$solution_file"
echo "# $problem_link" >> "$solution_file"

echo "$problem_name"
echo "$solution_file"
